### ISSUE TITLE
Starting block with colon throws an error

### ISSUE THREAD

**Issue by hsheth2** [joshtemple/lkml#90]
Similar to https://github.com/joshtemple/lkml/issues/82 - not super important on my end, but wanted to make you aware.

```
view: my_derived_view {
  derived_table: {:
    sql:
        SELECT
          col1,
        FROM
          ${my_view.SQL_TABLE_NAME} AS my_view ;;
  }
}
```

Note the `:` after the `{` on line 2 - turns out Looker's lkml parser will happily ignore the stray character. This causes an exception with `lkml`

```
Traceback (most recent call last):
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/bin/lkml", line 8, in <module>
    sys.exit(cli())
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/__init__.py", line 119, in cli
    result: dict = load(args.file)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/__init__.py", line 50, in load
    tree: DocumentNode = parse(text)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/__init__.py", line 29, in parse
    tree: DocumentNode = parser.parse()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 220, in parse
    container = self.parse_container()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 39, in wrapper
    result = fn(self, *args, **kwargs)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 244, in parse_container
    block = self.parse_block()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 39, in wrapper
    result = fn(self, *args, **kwargs)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 304, in parse_block
    container = self.parse_container()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 39, in wrapper
    result = fn(self, *args, **kwargs)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 244, in parse_container
    block = self.parse_block()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 39, in wrapper
    result = fn(self, *args, **kwargs)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 304, in parse_block
    container = self.parse_container()
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 39, in wrapper
    result = fn(self, *args, **kwargs)
  File "/Users/hsheth/projects/datahub/metadata-ingestion/venv/lib/python3.10/site-packages/lkml/parser.py", line 260, in parse_container
    raise SyntaxError(
SyntaxError: Unable to find a matching expression for ':' on line 2
```

It seems like you could modify `parse_container` to just consume `:` tokens when opening the block, but it does feel like a hack.

**Comment by joshtemple** [comment]
Thanks for reporting @hsheth2, but I'm afraid I'm not going to support this. This is just too esoteric...
