### ISSUE TITLE
Error when serializing query filters

### ISSUE THREAD

**Issue by dotans-delphi** [joshtemple/lkml#96]
The following demonstrates the error:
`>>> import lkml
>>> raw_lookml = """explore: foo { query: goo { filters: [zoo: "error"]}}"""
>>> content = lkml.load(raw_lookml)
>>> lkml.dump(content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/__init__.py", line 68, in dump
    tree: DocumentNode = parser.parse(obj)
                         ^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 266, in parse
    nodes = [self.parse_any(key, value) for key, value in obj.items()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 266, in <listcomp>
    nodes = [self.parse_any(key, value) for key, value in obj.items()]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 315, in parse_any
    return self.expand_list(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 290, in expand_list
    return flatten([self.parse_any(singular_key, value) for value in values])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 290, in <listcomp>
    return flatten([self.parse_any(singular_key, value) for value in values])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 324, in parse_any
    return self.parse_block(key, to_parse, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 346, in parse_block
    nodes = [self.parse_any(key, value) for key, value in items.items()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 346, in <listcomp>
    nodes = [self.parse_any(key, value) for key, value in items.items()]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 315, in parse_any
    return self.expand_list(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 290, in expand_list
    return flatten([self.parse_any(singular_key, value) for value in values])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 290, in <listcomp>
    return flatten([self.parse_any(singular_key, value) for value in values])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 324, in parse_any
    return self.parse_block(key, to_parse, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 346, in parse_block
    nodes = [self.parse_any(key, value) for key, value in items.items()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 346, in <listcomp>
    nodes = [self.parse_any(key, value) for key, value in items.items()]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 317, in parse_any
    return self.parse_list(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dotan/dev/delphi_backend/venv/lib/python3.11/site-packages/lkml/simple.py", line 409, in parse_list
    [(key, val)] = value.items()
                   ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'`

I've looked at the code and realized filters are a topic this library already confronted in the past. It doesn't look like the matter is resolved. Regretfully my lookml knowledge is not on par to be able to propose a working fix contribution, for that I apologize.

**Comment by joshtemple** [comment]
Ah, it's because of the behavior added in the fix for #53.

**Comment by joshtemple** [comment]
I've released the fix in v1.3.6 which should now be live on PyPI. Could you give it a try for me?

**Comment by joshtemple** [comment]
You’re welcome, glad it was a quick fix!
